### ISSUE TITLE
File/folder names with <>:"/\|?* are incompatible with Windows

### ISSUE THREAD

**Issue by PlaylistsTrance** [jensechu/bangya-data#17]
Example folders: class:y, ily:1, ze:a, iz*one. Please rename these so Windows users can correctly clone the repo and add images.

**Comment by jensechu** [comment]
Solved! I removed any non-alphanumeric characters. Thanks!

**Comment by PlaylistsTrance** [comment]
https://github.com/jensechu/bangya-data/tree/main/artists/everglow/members/e:u

Could you also do this for E:U?
