### ISSUE TITLE
Windows users still can't clone because of E:U folder

### ISSUE THREAD

**Issue by PlaylistsTrance** [jensechu/bangya-data#22]
Issue #17 was closed prematurely. Currently there's this folder https://github.com/jensechu/bangya-data/tree/main/artists/everglow/members/e:u which prevents Windows users from cloning due to the `:` character. Could this be replaced as well? Before closing this issue, please let me reply first after cloning to verify it works.

**Comment by jensechu** [comment]
Flagging this as a won't fix because its fine on unix/mac and we will get a web UI up for people to collaborate soon and hide this repo.

**Comment by PlaylistsTrance** [comment]
Oh that's even better. Thanks!
